name: ml
channels:
- pytorch
- defaults
dependencies:
- pytorch=1.7.1
- pip=21.0.1
- torchvision=0.8.2
- pandas==1.0.3
- numpy=1.18.1
- scipy=1.4.1
- seaborn=0.10.0
- dill==0.3.3
- tqdm==4.49.0
- jupyter=1.0.0
- jupyter_client=5.3.4
- jupyter_console=6.1.0
- jupyter_core=4.6.1
- jupyterlab=1.2.6
- jupyterlab_server=1.0.6
- pillow=7.0.0
- beautifulsoup4
- pip:
    - cox
    - ftfy
    - regex
    - statsmodels
    - cleanlab
    - omegaconf
    - wandb
    - scikit-image
    - torch==1.9.0
    - torchfile==0.1.0
    - torchtext==0.7.0
    - torchvision==0.10.0
    - tqdm==4.48.2
    - transformers==4.5.0
    - attrdict